### ISSUE TITLE
3D maybe improved label readability and removed calcs on max-width of elements

### ISSUE THREAD

**Issue by danidomen** [mmomtchev/scodex#3]
Hi @mmomtchev!

This project is fucking fucking incredible. Its like a dream for me because is a real star map where you can track where you are at and the location of the things in fucking real time!!!

I make some adjustments to the CSS to improve the readability of the labels because I mix a bit with the white & gray and, maybe has a good reason, but always the site has a right blank margin and the website don't taking all the full width screen.

I share what changes I do:
```
    .header{
        max-width: 100%
    }
    .main{
        max-width: 100%;
        background-size: 100%;
        background-image: url("https://starslog.io/images/space_background.png");
        background-position: cover;
        overflow-y: initial;
    }
    .footer{
        max-width: 100%;
    }
    

    .label {
        background: rgba(0,0,0,0.3);
        font-size: 10px;
        padding: 2px;
        color: #efff00;
        border-radius: 10px;
        padding: 1px 14px;
    }
    .label.label-unknown{
        color: #9ae3f3
    }
```
And I have this view now:
![image](https://user-images.githubusercontent.com/5998908/213495729-ec81f9d9-b34f-49c5-8f53-6b8fc4d5c9ec.png)

You can send me to shit, but I promise I will continue to use this wonder of web app.

Best!

**Comment by mmomtchev** [comment]
I agree that it looks much better, I will look into adding some of it - what is the copyright status of this image, where does it come from?

**Comment by danidomen** [comment]
Hi @mmomtchev! Originally the background image I take from here (true that say not copyright found but doesnt mean it doesnt have it): https://www.dualmonitorbackgrounds.com/astronomy/vastspace.jpg.php

I modified a bit with darker color, but anyway it doesn't mean you must use that image. For example, with this prompt at Dall-E I generated some images that can be used or altered on any non or commercial project and are of your own (https://labs.openai.com/about on Usage & Rights):
![image](https://user-images.githubusercontent.com/5998908/213752617-ea9e8f0d-19fc-4001-8673-e9bc4829c335.png)

**Comment by danidomen** [comment]
I created this one through DALL-E and reedited with PhotoShop to darker it and make it tileable, so this one is totally free to use (you can download, use it or edit it): https://starslog.io/images/space_background_for_scodex_garga.jpg & darker one https://starslog.io/images/space_background_for_scodex_garga_dark.jpg

For that, the styles for the main need to be like:
```
.main {
        max-width: 100%;
        background-size: auto;
        background-image: url("https://starslog.io/images/space_background_for_scodex_garga.jpg");
        background-repeat: repeat;
        overflow-y: initial;
}
```

And the result is like this:
![image](https://user-images.githubusercontent.com/5998908/213918229-73cc1dd5-d200-4f16-9d03-ade901628d22.png)

What do you think?
