### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by danidomen** [mmomtchev/scodex#4]
Hi @mmomtchev ,

The website shows "Somehow you managed to reach the still not-implemented Pyro Jump Point" and you cannot access to any part of the site.

![image](https://user-images.githubusercontent.com/5998908/223451971-d554fc68-10c9-44d8-893b-3a6bfdec5726.png)

Also on the "Select version" no any version shows up
![image](https://user-images.githubusercontent.com/5998908/223452192-2cc96c7f-0239-4aea-b60f-b9bf6ba4b7cd.png)

**Comment by mmomtchev** [comment]
It is working for me, are you trying to access a specific URL?

**Comment by danidomen** [comment]
Wow, yes, its working and I see the problem. It was the URL, I don't know how I ended to https://scodex-test.garga.net/ instead to https://scodex.garga.net/
