### ISSUE TITLE
2D Tiles not rendering - Error 502 on https://scodex.b-cdn.net/

### ISSUE THREAD

**Issue by danidomen** [mmomtchev/scodex#5]
Hi @mmomtchev 

All the planets and moons have missing tiles on the "2D" version. If you zoom it it loads the HD version, but the first SD load have missing tiles.  

![image](https://user-images.githubusercontent.com/5998908/230746857-5af8d8bb-5024-4fa9-8df3-3a0d8eab9ca4.png)

I checked the console and get some 502 on the CDN
![image](https://user-images.githubusercontent.com/5998908/230746924-3b7e7973-cc87-48cb-a8bd-47d571d36ca2.png)

For example, one of them:
https://scodex.b-cdn.net/map/Arial/tile-1-3-0.png

![image](https://user-images.githubusercontent.com/5998908/230746940-3ebad1e1-46ea-412a-bdc1-d89b0a1730c6.png)

**Comment by mmomtchev** [comment]
It was due to a hardware failure at the CDN provider, data is being restored as we speak

Thanks for reporting this
